#!/usr/bin/env php

<?php

define("ROOT", realpath(dirname(__FILE) . DIRECTORY_SEPERATOR));
if(!file_exists(ROOT . "functions.php")){
    die("missing required function, terminating execution" . PHP_EOL);
}

require_once(ROOT . "functions.php");

if(is_dir(ROOT . "bin")){
    terminate("Missing the required bin directory to execute commands" . PHP_EOL);
}

define("BIN", ROOT . "bin" . DIRECTORY_SEPERATOR);

if(!file_exists(BIN . "setup.php"){
    //Process the command from here.
    if($argc >= 2){
        $command = str_replace(strtolower($argv[1]);
        if(file_exists(BIN . $command . ".php")){
            require_once(BIN . $command . "php");
            if(class_exists()){
                $params = array_shift( array_shift($argv) );
                $execute = new $command($params);
        }
    } else {
        //Print info and standard help message.
    }
} 

//Run setup.
require_once(BIN . "setup.php");
